### PR TITLE
add DNS level enforcement

### LINKED ISSUE #2556: Enforcement & auditing for DNS
Implement network enforcement on DNS 

Proposed Policy Spec
```
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
 name: dns-enforcement
 namespace: multiubuntu
spec:
 selector:
   matchLabels:
    group: group-1
 network:
   matchDNS:
     - fqdn: "<name>"
       fromSource:
         - path: /usr/bin/curl
       action: Block
       message: “fqdn blocked"
 action: Allow/Block/Audit
```

### PR DESCRIPTION
**Pull request by Aryan-sharma11**
**Purpose of PR?**:

Fixes #2556 

**Does this PR introduce a breaking change?**

**If the changes in this PR are manually verified, list down the scenarios covered:**:

**Additional information for reviewer?** :
_Mention if this PR is part of any design or a continuation of previous PRs_

**Checklist:**
- [ ] Bug fix. Fixes #<issue number>
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] PR Title follows the convention of  `<type>(<scope>): <subject>`
- [ ] Commit has unit tests
- [ ] Commit has integration tests

### CODE REVIEW

**Review by AryanBakliwal — COMMENTED** [review]
@Aryan-sharma11 I tested this. Allow, Audit, and Block policies are all functioning correctly.
Ubuntu 24.04.4 LTS
Kernel v6.17.0-22-generic

**Review by rksharma95 — CHANGES_REQUESTED** [review]
failed to compile on kernel 5.15

PTAL here, we're handling the same in system monitor as well, also enforcement would be supported on BTF supported systems only but we need to test it on RHEL distro as it requires additional handling.

https://github.com/kubearmor/KubeArmor/blob/8032c3747d298bf324da1f23cb40496d38511565/KubeArmor/BPF/system_monitor.c#L2556-L2561

```
cd /home/vagrant/KubeArmor/KubeArmor; bpftool btf dump file /sys/kernel/btf/vmlinux format c > BPF/vmlinux.h || true
if grep -q bpf '/sys/kernel/security/lsm'; then \
        cd /home/vagrant/KubeArmor/KubeArmor; go generate ./... || true; \
fi
/home/vagrant/KubeArmor/KubeArmor/BPF/enforcer.bpf.c:960:43: error: no member named '__iov' in 'struct iov_iter'
  if (bpf_core_field_exists(msg->msg_iter.__iov))
                            ~~~~~~~~~~~~~ ^
/usr/include/bpf/bpf_core_read.h:120:32: note: expanded from macro 'bpf_core_field_exists'
        __builtin_preserve_field_info(field, BPF_FIELD_EXISTS)
                                      ^~~~~
/home/vagrant/KubeArmor/KubeArmor/BPF/enforcer.bpf.c:963:61: error: no member named '__iov' in 'struct iov_iter'
    bpf_probe_read_kernel(&iov, sizeof(iov), &msg->msg_iter.__iov);
                                              ~~~~~~~~~~~~~ ^
2 errors generated.
Error: compile: exit status 1
exit status 1
enforcer/bpflsm/enforcer.go:29: running "go": exit status 1
/home/vagrant/KubeArmor/KubeArmor/BPF/ima_hash.bpf.c:27:16: warning: implicit declaration of function 'bpf_ima_file_hash' is invalid in C99 [-Wimplicit-function-declaration]
    u32 algo = bpf_ima_file_hash(bprm->file, hash.digest, sizeof(hash.digest));
               ^
1 warning generated.
/home/vagrant/KubeArmor/KubeArmor/BPF/ima_hash.bpf.c:27:16: warning: implicit declaration of function 'bpf_ima_file_hash' is invalid in C99 [-Wimplicit-function-declaration]
    u32 algo = bpf_ima_file_hash(bprm->file, hash.digest, sizeof(hash.digest));
               ^
1 warning generated.
cd /home/vagrant/KubeArmor/KubeArmor; CGO_ENABLED=0 go build -ldflags "-X github.com/kubearmor/KubeArmor/KubeArmor/buildinfo.BuildDate=2026-04-30T08:25:07Z -X github.com/kubearmor/KubeArmor/KubeArmor/buildinfo.GitCommit=080cbd91 -X github.com/kubearmor/KubeArmor/KubeArmor/buildinfo.GitBranch=HEAD -X github.com/kubearmor/KubeArmor/KubeArmor/buildinfo.GitState=dirty -X github.com/kubearmor/KubeArmor/KubeArmor/buildinfo.GitSummary=v1.6.14-62-g080cbd91-dirty" -o kubearmor main.go
^[[A^[[B^[[Benforcer/bpflsm/enforcer_bpfel.go:220:12: pattern enforcer_bpfel.o: no matching files found
make: *** [Makefile:28: build] Error 1
vagrant@kubearmor-dev-next:~/KubeArmor/KubeArmor$ uname -r
5.15.0-91-generic
```

File: KubeArmor/BPF/enforcer.bpf.c [hunk 1]
```diff
@@ -808,4 +810,173 @@ int BPF_PROG(enforce_cap, const struct cred *cred, struct user_namespace *ns,
...
+
+  __u16 dport = 0;
+  bpf_probe_read(&dport, sizeof(dport), &sk->__sk_common.skc_dport);
+  if (bpf_ntohs(dport) != 53)
+    return 0;
+
+  struct iovec *iovp = NULL;
+  void *data = NULL;
+
+#if LINUX_VERSION_CODE >= KERNEL_VERSION(6, 3, 13) || RHEL9_BUILD_GTE_400
```
Comment (rksharma95) [inline KubeArmor/BPF/enforcer.bpf.c]: we have a problem here, the point is we cannot depend upon any conditional compilation flag. as we'll not compile bpflsm enforcer on target host. also irrelevant but we cannot use RHEL9_BUILD_GTE_400.

**Review by rksharma95 — CHANGES_REQUESTED** [review]

**Comment by rksharma95** [comment]
:heavy_check_mark: working as expected,

just for **note**, as it support absolute dns matching, it's the policy that need to be crafted carefully.

i.e. in the test policy google.com would be blocked but www.google.com would work.

```
❯ kubectl version
Client Version: v1.31.5+k3s1
Kustomize Version: v5.4.2
Server Version: v1.31.5+k3s1
❯ kubectl get nodes -o wide
NAME        STATUS   ROLES                  AGE    VERSION        INTERNAL-IP      EXTERNAL-IP   OS-IMAGE     KERNEL-VERSION   CONTAINER-RUNTIME
archlinux   Ready    control-plane,master   440d   v1.31.5+k3s1   192.168.29.159   <none>        Arch Linux   6.12.67-1-lts    containerd://1.7.23-k3s2
```

```
== Alert / 2026-05-06 11:32:24.780005 ==
ClusterName: default
HostName: archlinux
NamespaceName: default
PodName: nginx-855564d959-k2rjh
Labels: app=nginx
ContainerName: nginx
ContainerID: 29c82a9718c58df7d735148b4e6a2171bc042a2cef0118f164c0cc5873b07566
ContainerImage: docker.io/library/nginx:latest@sha256:6e23479198b998e5e25921dff8455837c7636a67111a04a635cf1bb363d199dc
Type: MatchedPolicy
PolicyName: block-dns-query-to-google
Severity: 10
Message: Blocked curl query to google.com
Source: /usr/bin/curl google.com
Resource: google.com
Operation: Network
Action: Audit
Data: kfunc=UDP_SENDMSG domain=google.com.cluster.local daddr=10.43.0.10 qtype=AAAA
EventData: map[Daddr:10.43.0.10 Domain:google.com.cluster.local Kfunc:UDP_SENDMSG Qtype:AAAA]
Enforcer: eBPF Monitor
Result: Passed
Cwd: /
ExecEvent: map[ExecID:1711198194048767 ExecutableName:curl]
HostPID: 398419
HostPPID: 394944
Owner: map[Name:nginx Namespace:default Ref:Deployment]
PID: 72
PPID: 64
ParentProcessName: /usr/bin/bash
ProcessName: /usr/bin/curl
TTY: pts1
UID: 0
== Alert / 2026-05-06 11:32:24.780247 ==
ClusterName: default
HostName: archlinux
NamespaceName: default
PodName: nginx-855564d959-k2rjh
Labels: app=nginx
ContainerName: nginx
ContainerID: 29c82a9718c58df7d735148b4e6a2171bc042a2cef0118f164c0cc5873b07566
ContainerImage: docker.io/library/nginx:latest@sha256:6e23479198b998e5e25921dff8455837c7636a67111a04a635cf1bb363d199dc
Type: MatchedPolicy
PolicyName: block-dns-query-to-google
Severity: 10
Message: Blocked curl query to google.com
Source: /usr/bin/curl google.com
Resource: google.com
Operation: Network
Action: Audit
Data: kfunc=UDP_SENDMSG domain=google.com daddr=10.43.0.10 qtype=AAAA
EventData: map[Daddr:10.43.0.10 Domain:google.com Kfunc:UDP_SENDMSG Qtype:AAAA]
Enforcer: eBPF Monitor
Result: Passed
Cwd: /
ExecEvent: map[ExecID:1711198194048767 ExecutableName:curl]
HostPID: 398419
HostPPID: 394944
Owner: map[Name:nginx Namespace:default Ref:Deployment]
PID: 72
PPID: 64
ParentProcessName: /usr/bin/bash
ProcessName: /usr/bin/curl
TTY: pts1
UID: 0
== Alert / 2026-05-06 11:32:24.780245 ==
ClusterName: default
HostName: archlinux
NamespaceName: default
PodName: nginx-855564d959-k2rjh
Labels: app=nginx
ContainerName: nginx
ContainerID: 29c82a9718c58df7d735148b4e6a2171bc042a2cef0118f164c0cc5873b07566
ContainerImage: docker.io/library/nginx:latest@sha256:6e23479198b998e5e25921dff8455837c7636a67111a04a635cf1bb363d199dc
Type: MatchedPolicy
PolicyName: block-dns-query-to-google
Severity: 10
Message: Blocked curl query to google.com
Source: /usr/bin/curl google.com
Resource: google.com
Operation: Network
Action: Audit
Data: kfunc=UDP_SENDMSG domain=google.com daddr=10.43.0.10 qtype=A
EventData: map[Daddr:10.43.0.10 Domain:google.com Kfunc:UDP_SENDMSG Qtype:A]
Enforcer: eBPF Monitor
Result: Passed
Cwd: /
ExecEvent: map[ExecID:1711198194048767 ExecutableName:curl]
HostPID: 398419
HostPPID: 394944
Owner: map[Name:nginx Namespace:default Ref:Deployment]
PID: 72
PPID: 64
ParentProcessName: /usr/bin/bash
ProcessName: /usr/bin/curl
TTY: pts1
UID: 0
```

image

**Review by rksharma95 — DISMISSED** [review]

**Review by AryanBakliwal — DISMISSED** [review]

**Comment by Aryan-sharma11** [comment]
Tested on Talos Env 
``` 
Defaulted container "kubearmor" out of: kubearmor, init (init)
2026-05-07 11:19:58.131423	INFO	BUILD-INFO: version: v1.6.16-52-g9b654278-dirty, branch: dns-enforcement, date: 2026-05-07T10:48:18Z
2026-05-07 11:19:58.131722	INFO	Arguments [alertThrottling:true annotateResources:false bpfFsPath:/sys/fs/bpf cluster:default coverageTest:false criSocket: debug:false defaultCapabilitiesPosture:audit defaultFilePosture:audit defaultNetworkPosture:audit defaultPostureLogs:true dropResourceFromProcessLogs:false enableIMA:false enableKubeArmorHostPolicy:false enableKubeArmorPolicy:true enableKubeArmorStateAgent:false enableKubeArmorVm:false enableNRI:false enableNetworkPolicyEnforcer:true enableUSBDeviceHandler:false enforcerAlerts:true gRPC:32767 host:talos-f6g-dgz hostDefaultCapabilitiesPosture:audit hostDefaultDevicePosture:audit hostDefaultFilePosture:audit hostDefaultNetworkPosture:audit hostVisibility:default initTimeout:60s k8s:true kubeconfig: logPath:none lsm:bpf,apparmor,selinux machineIDPath:/etc/machine-id matchArgs:true maxAlertPerSec:10 nriIndex:99 nriSocket: procfsMount:/proc seLinuxProfileDir:/tmp/kubearmor.selinux throttleSec:30 tlsCertPath:/var/lib/kubearmor/tls tlsCertProvider:self tlsEnabled:false untrackedNs:kube-system,kubearmor useOCIHooks:false visibility:process,file,network,capabilities]
2026-05-07 11:19:58.131840	INFO	Configuration [{Cluster: Host: GRPC: TLSEnabled:false TLSCertPath: TLSCertProvider: LogPath: SELinuxProfileDir: CRISocket: NRISocket: NRIIndex: NRIEnabled:false Visibility: HostVisibility: EnableIMA:false Policy:false HostPolicy:false KVMAgent:false K8sEnv:false Debug:false DefaultFilePosture: DefaultNetworkPosture: DefaultCapabilitiesPosture: HostDefaultFilePosture: HostDefaultNetworkPosture: HostDefaultCapabilitiesPosture: HostDefaultDevicePosture: CoverageTest:false ConfigUntrackedNs:{v:<nil>} LsmOrder:[] BPFFsPath: EnforcerAlerts:false DefaultPostureLogs:false InitTimeout: StateAgent:false UseOCIHooks:false AlertThrottling:false MaxAlertPerSec:0 ThrottleSec:0 AnnotateResources:false ProcFsMount: DropResourceFromProcessLogs:false MachineIDPath: USBDeviceHandler:false MatchArgs:false NetworkPolicyEnforcer:false}]
2026-05-07 11:19:58.131954	INFO	Final Configuration [{Cluster:default Host:talos-f6g-dgz GRPC:32767 TLSEnabled:false TLSCertPath:/var/lib/kubearmor/tls TLSCertProvider:self LogPath:none SELinuxProfileDir:/tmp/kubearmor.selinux CRISocket: NRISocket: NRIIndex:99 NRIEnabled:false Visibility:process,file,network,capabilities HostVisibility:none EnableIMA:false Policy:true HostPolicy:false KVMAgent:false K8sEnv:true Debug:false DefaultFilePosture:audit DefaultNetworkPosture:audit DefaultCapabilitiesPosture:audit HostDefaultFilePosture:audit HostDefaultNetworkPosture:audit HostDefaultCapabilitiesPosture:audit HostDefaultDevicePosture:audit CoverageTest:false ConfigUntrackedNs:{v:[kube-system kubearmor]} LsmOrder:[bpf apparmor selinux] BPFFsPath:/sys/fs/bpf EnforcerAlerts:true DefaultPostureLogs:true InitTimeout:60s StateAgent:false UseOCIHooks:false AlertThrottling:true MaxAlertPerSec:10 ThrottleSec:30 AnnotateResources:false ProcFsMount:/host/procfs DropResourceFromProcessLogs:false MachineIDPath:/etc/machine-id USBDeviceHandler:false MatchArgs:true NetworkPolicyEnforcer:true}]
2026-05-07 11:19:58.131992	INFO	Final Configuration [{Cluster:default Host:talos-f6g-dgz GRPC:32767 TLSEnabled:false TLSCertPath:/var/lib/kubearmor/tls TLSCertProvider:self LogPath:none SELinuxProfileDir:/tmp/kubearmor.selinux CRISocket: NRISocket: NRIIndex:99 NRIEnabled:false Visibility:process,file,network,capabilities HostVisibility:none EnableIMA:false Policy:true HostPolicy:false KVMAgent:false K8sEnv:true Debug:false DefaultFilePosture:audit DefaultNetworkPosture:audit DefaultCapabilitiesPosture:audit HostDefaultFilePosture:audit HostDefaultNetworkPosture:audit HostDefaultCapabilitiesPosture:audit HostDefaultDevicePosture:audit CoverageTest:false ConfigUntrackedNs:{v:[kube-system kubearmor]} LsmOrder:[bpf apparmor selinux] BPFFsPath:/sys/fs/bpf EnforcerAlerts:true DefaultPostureLogs:true InitTimeout:60s StateAgent:false UseOCIHooks:false AlertThrottling:true MaxAlertPerSec:10 ThrottleSec:30 AnnotateResources:false ProcFsMount:/host/procfs DropResourceFromProcessLogs:false MachineIDPath:/etc/machine-id USBDeviceHandler:false MatchArgs:true NetworkPolicyEnforcer:true}]
2026-05-07 11:19:58.132772	INFO	Initialized Kubernetes client
2026-05-07 11:19:58.132819	INFO	Started to monitor node events
2026-05-07 11:19:58.132874	INFO	GlobalCfg.Host=talos-f6g-dgz, KUBEARMOR_NODENAME=talos-f6g-dgz
2026-05-07 11:19:58.132970	INFO	Started watching node information
2026-05-07 11:19:59.133349	INFO	Node Name: talos-f6g-dgz
2026-05-07 11:19:59.133497	INFO	Node IP: 192.168.100.149
2026-05-07 11:19:59.133524	INFO	Node ID: talos-f6g-dgz
2026-05-07 11:19:59.133569	INFO	Node Annotations: map[flannel.alpha.coreos.com/backend-data:{"VNI":1,"VtepMAC":"56:d3:eb:46:e4:cf"} flannel.alpha.coreos.com/backend-type:vxlan flannel.alpha.coreos.com/kube-subnet-manager:true flannel.alpha.coreos.com/public-ip:192.168.100.149 kubearmor-policy:enabled kubearmor-visibility:none node.alpha.kubernetes.io/ttl:0 volumes.kubernetes.io/controller-managed-attach-detach:true]
2026-05-07 11:19:59.133592	INFO	OS Image: Talos (v1.13.0)
2026-05-07 11:19:59.133616	INFO	Kernel Version: 6.18.24-talos
2026-05-07 11:19:59.133681	INFO	Kubelet Version: v1.36.0
2026-05-07 11:19:59.133705	INFO	Container Runtime: containerd://2.2.3
2026-05-07 11:19:59.142600	INFO	Initialized KubeArmor Logger
2026-05-07 11:19:59.145418	INFO	Mounting BPF Filesystem at /sys/fs/bpf
2026-05-07 11:19:59.149000	INFO	Initializing eBPF system monitor
2026-05-07 11:19:59.171506	INFO	Successfully added visibility map with key={PidNS:0 MntNS:0} to the kernel
2026-05-07 11:19:59.211565	INFO	Successfully added visibility map with key={PidNS:12648430 MntNS:12648430} to the kernel
2026-05-07 11:19:59.211881	INFO	Alert Throttling configured {alertThrottling:true, maxAlertPerSec:10, throttleSec:30}
2026-05-07 11:19:59.211921	INFO	Argument matching configured {matchArgs:true}
2026-05-07 11:19:59.211938	INFO	eBPF system monitor object file path: /opt/kubearmor/BPF/system_monitor.bpf.o
2026-05-07 11:20:01.447233	INFO	Initialized the eBPF system monitor
2026-05-07 11:20:01.566035	WARN	error:[syscalls sys_exit_openat]: neither debugfs nor tracefs are mounted
2026-05-07 11:20:01.566103	WARN	error:[syscalls sys_enter_setns]: neither debugfs nor tracefs are mounted
2026-05-07 11:20:01.566113	WARN	error:[syscalls sys_exit_setns]: neither debugfs nor tracefs are mounted
2026-05-07 11:20:01.566140	WARN	error:[sched sched_process_fork]: neither debugfs nor tracefs are mounted
2026-05-07 11:20:01.620304	INFO	Initialized KubeArmor Monitor
2026-05-07 11:20:01.620355	INFO	Started to monitor system events
2026-05-07 11:20:01.622683	INFO	Supported LSMs: lockdown,capability,yama,selinux,bpf,landlock
2026-05-07 11:20:09.764451	INFO	Initialized BPF-LSM Enforcer
2026-05-07 11:20:09.764507	INFO	Initialized KubeArmor Enforcer
2026-05-07 11:20:09.764515	INFO	Started to protect containers
2026-05-07 11:20:09.764630	INFO	Starting TraceEvents from BPF LSM Enforcer
2026-05-07 11:20:09.809178	INFO	Starting TraceEvents from AnonMapExec Presets
2026-05-07 11:20:09.858475	INFO	Starting TraceEvents from FilelessExec Presets
2026-05-07 11:20:09.946183	INFO	Starting TraceEvents from ProtectEnv Presets
2026-05-07 11:20:10.028297	INFO	Starting TraceEvents from Exec Presets
2026-05-07 11:20:10.110524	INFO	Initialized Presets
2026-05-07 11:20:10.110595	INFO	Using runtime and CRI socket detected by snitch
2026-05-07 11:20:10.110711	INFO	Starting TraceEvents from ProtectProc Presets
2026-05-07 11:20:10.111615	INFO	Started to monitor Containerd events
2026-05-07 11:20:10.116263	WARN	Failed to update containerd container e30ba845fda2327f50876d8c21849a1235547e5f61c195a54f1ce159b7becb9f: skipping pause/moby container: pause container
2026-05-07 11:20:10.116940	WARN	Failed to update containerd container 562af6e66014c3835ac2b710df5c6d2b0619cce8db23abb7284ecdfed7e4738e: skipping pause/moby container: pause container
2026-05-07 11:20:10.117502	WARN	Failed to update containerd container 17a3c0db007ff537191f2836e39e532a2b16bb2c0af91f760cf29ce6ad2ea9c2: skipping pause/moby container: pause container
2026-05-07 11:20:10.120583	WARN	Failed to update containerd container 364d463b52995cb389dfee6ef5a75f9e38e91f0442410d71d2373228ce36bea5: failed to get container info: rpc error: code = NotFound desc = task 364d463b52995cb389dfee6ef5a75f9e38e91f0442410d71d2373228ce36bea5 not found
2026-05-07 11:20:10.121896	WARN	Failed to update containerd container 3a92d82c0a64a6b35eaeffa5d9733d6b0dbd3cbb125a126b5db2e4c51be21f57: failed to get container info: rpc error: code = NotFound desc = task 3a92d82c0a64a6b35eaeffa5d9733d6b0dbd3cbb125a126b5db2e4c51be21f57 not found
2026-05-07 11:20:10.122294	WARN	Failed to update containerd container 3be88cec3eb179fb12b43a82e1174c3ed441b1413a3ff2a99b3b02ddc53f1a78: skipping pause/moby container: pause container
2026-05-07 11:20:10.159588	INFO	Successfully added visibility map with key={PidNS:4026532762 MntNS:4026532761} to the kernel
2026-05-07 11:20:10.159642	INFO	[ProtectProc] Registered container with id: 4e0c9a07b48f097e758d2ddf20852fbb2e94786867e28a7e83b4cd881acdcfdc
```
image

**Review by rksharma95 — APPROVED** [review]

**Review by AryanBakliwal — APPROVED** [review]

**Comment by soorya-knox** [comment]
@Aryan-sharma11 to provide a documentation
